language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
os: linux
branches:
  only:
    - master # build master branch only
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  strategy: git
  provider: pages
  skip_cleanup: true
  token: $GH_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: public
