# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 枫之谷
subtitle: 这个人很懒，但还是想留下些什么东西。
description:
author: Duang
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://zakum.cn
root: /
permalink: posts/:abbrlink/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
permalink_defaults:

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ' '

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: Yelee
# theme: yilia
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/realDuang/blog.git
  branch: gh-pages
  ignore_hidden: false

include:
  .nojekyll

sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

live2d:
  enable: true
  scriptFrom: jsdelivr
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  log: false
  model:
    use: live2d-widget-model-koharu
    scale: 0.75
  display:
    position: right
    hOffset: 0
    vOffset: -80
  mobile:
    show: false
  dialog:
    enable: true
    hitokoto: true
  react:
    opacityDefault: 0.8
    opacityOnHover: 0.2

symbols_count_time:
  # 文章上部是否显示字数
  symbols: true
  # 文章上部是否显示阅读时间
  time: true
  # 站点底端是否显示站点总字数
  total_symbols: false
  # 站点底端是否显示总阅读时间
  total_time: false
  # 是否移除代码块
  exclude_codeblock: false
  awl: 4
  wpm: 200

# abbrlink config 把标题转成唯一的英文或数字字符串
abbrlink:
  alg: crc16  #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex